# Uncomment the next line to define a global platform for your project
target 'EUILayoutDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  target 'EUILayoutDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EUILayoutDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
