# Uncomment the next line to define a global platform for your project
target 'DCContainerLayouter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for DCContainerLayouter
  pod 'YogaKit', '~> 1.7'

  target 'DCContainerLayouterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DCContainerLayouterUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
